[paths]
# Define the relative paths to your data folders from the root of your project
analysis_outputs = "data/analysis-outputs"
processed = "data/processed"
raw = "data/raw"

[files]
# List the filenames for each data source
enrollments = "country_enrollment_summary.csv"
assessments_by_course = "course_assessment_by_course.csv"
city_clusters = "city_cluster_distribution.csv"
experiment = "experiment_curriculum_cleaned.csv"
pca_workbook = "pca_components.xlsx"
kmeans_centers = "pca_kmeans_results.xlsx"
survey_questions = "survey_questions.xlsx"

[settings]
# Define your cluster persona labels here
[settings.cluster_labels]
"Cluster 0" = "Career-Oriented Implementers"
"Cluster 1" = "Operational Specialists"
"Cluster 2" = "Skill Growth Seekers"
"Cluster 3" = "Foundation Builders"
